apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-binding
  namespace: apple
roleRef: # points to the Role
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-reader-role # name of Role
subjects: # points to the ServiceAccount
- kind: ServiceAccount
  name: apple-sa # service account to bind to
  namespace: apple # ns of service account